CREATE TABLE consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_name VARCHAR(120) NOT NULL,
    date_time TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('SCHEDULED','COMPLETED','CANCELLED')),
    reason VARCHAR(500) NOT NULL
);
CREATE INDEX idx_consultas_patient_date ON consultas(patient_id, date_time);
