spring.application.name=graphql-api
server.port=8081

spring.grpc.client.channel.patient-service.target=static://${PATIENT_SERVICE_HOST:localhost}:9090
spring.grpc.client.channel.agendamento-service.target=static://${AGENDAMENTO_SERVICE_HOST:localhost}:9091

spring.graphql.graphiql.enabled=true

spring.datasource.url=jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

jwt.secret=${JWT_SECRET:oN3/gkdGOWKQ2zvz3oKZnTJUU3VtSAlPTUDdKypyLPw=}
jwt.expiration-ms=3600000
