spring.application.name=graphql-api
server.port=8081

spring.grpc.client.channel.patient-service.target=static://localhost:9090
spring.grpc.client.channel.agendamento-service.target=static://localhost:9091

spring.graphql.graphiql.enabled=true
