spring.application.name=graphql-api
server.port=8081

spring.grpc.client.channel.patient-service.target=static://${PATIENT_SERVICE_HOST:localhost}:9090
spring.grpc.client.channel.agendamento-service.target=static://${AGENDAMENTO_SERVICE_HOST:localhost}:9091

spring.graphql.graphiql.enabled=true

spring.datasource.url=${AUTH_DB_URL:jdbc:postgresql://localhost:5434/authdb}
spring.datasource.username=${AUTH_DB_USER:caresync}
spring.datasource.password=${AUTH_DB_PASSWORD:caresync}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET:oN3/gkdGOWKQ2zvz3oKZnTJUU3VtSAlPTUDdKypyLPw=}
jwt.expiration-ms=3600000
