CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN','MEDICO','ENFERMEIRO','PACIENTE')),
    patient_id BIGINT,
    CONSTRAINT ck_patient_role CHECK ((role = 'PACIENTE' AND patient_id IS NOT NULL AND patient_id > 0) OR (role <> 'PACIENTE' AND patient_id IS NULL))
);
